package uz.tarjima.kitob

object PhrasesData {

    val categories: List<String> = listOf(
        "Barchasi",
        "Salomlashuv",
        "Raqamlar",
        "Vaqt va sana",
        "Oila",
        "Taomlar",
        "Transport",
        "Xarid",
        "Sog'liq",
        "Ranglar",
        "Foydali iboralar"
    )

    private val raw: List<Triple<String, String, String>> = listOf(
        Triple("Salomlashuv", "Salom", "Здравствуйте"),
        Triple("Salomlashuv", "Qandaysiz?", "Как дела?"),
        Triple("Salomlashuv", "Yaxshi, rahmat", "Хорошо, спасибо"),
        Triple("Salomlashuv", "Tanishganimdan xursandman", "Приятно познакомиться"),
        Triple("Salomlashuv", "Ismingiz nima?", "Как вас зовут?"),
        Triple("Salomlashuv", "Mening ismim...", "Меня зовут..."),
        Triple("Salomlashuv", "Xayr!", "До свидания!"),
        Triple("Salomlashuv", "Ertaga ko'rishamiz", "До завтра"),
        Triple("Salomlashuv", "Kechirasiz", "Извините"),
        Triple("Salomlashuv", "Iltimos", "Пожалуйста"),
        Triple("Salomlashuv", "Rahmat", "Спасибо"),
        Triple("Salomlashuv", "Arzimaydi", "Не за что"),
        Triple("Salomlashuv", "Ha", "Да"),
        Triple("Salomlashuv", "Yo'q", "Нет"),
        Triple("Salomlashuv", "Gap tushunmadim", "Я не понял(а)"),
        Triple("Salomlashuv", "Buni qayta ayting", "Повторите, пожалуйста"),
        Triple("Raqamlar", "Bir", "Один"),
        Triple("Raqamlar", "Ikki", "Два"),
        Triple("Raqamlar", "Uch", "Три"),
        Triple("Raqamlar", "To'rt", "Четыре"),
        Triple("Raqamlar", "Besh", "Пять"),
        Triple("Raqamlar", "Olti", "Шесть"),
        Triple("Raqamlar", "Yetti", "Семь"),
        Triple("Raqamlar", "Sakkiz", "Восемь"),
        Triple("Raqamlar", "To'qqiz", "Девять"),
        Triple("Raqamlar", "O'n", "Десять"),
        Triple("Raqamlar", "O'n besh", "Пятнадцать"),
        Triple("Raqamlar", "Yigirma", "Двадцать"),
        Triple("Raqamlar", "Yuz", "Сто"),
        Triple("Raqamlar", "Ming", "Тысяча"),
        Triple("Raqamlar", "Qancha?", "Сколько?"),
        Triple("Vaqt va sana", "Bugun", "Сегодня"),
        Triple("Vaqt va sana", "Erta", "Завтра"),
        Triple("Vaqt va sana", "Kecha", "Вчера"),
        Triple("Vaqt va sana", "Hozir", "Сейчас"),
        Triple("Vaqt va sana", "Soat nechada?", "В котором часу?"),
        Triple("Vaqt va sana", "Ertalab", "Утром"),
        Triple("Vaqt va sana", "Kunduzi", "Днём"),
        Triple("Vaqt va sana", "Kechqurun", "Вечером"),
        Triple("Vaqt va sana", "Tun", "Ночью"),
        Triple("Vaqt va sana", "Hafta", "Неделя"),
        Triple("Vaqt va sana", "Oy", "Месяц"),
        Triple("Vaqt va sana", "Yil", "Год"),
        Triple("Vaqt va sana", "Dushanba", "Понедельник"),
        Triple("Vaqt va sana", "Yakshanba", "Воскресенье"),
        Triple("Vaqt va sana", "Daqiqa", "Минута"),
        Triple("Oila", "Ona", "Мать"),
        Triple("Oila", "Ota", "Отец"),
        Triple("Oila", "Aka", "Старший брат"),
        Triple("Oila", "Uka", "Младший брат"),
        Triple("Oila", "Opa", "Старшая сестра"),
        Triple("Oila", "Singil", "Младшая сестра"),
        Triple("Oila", "Bobo", "Дедушка"),
        Triple("Oila", "Buvi", "Бабушка"),
        Triple("Oila", "Farzand", "Ребёнок"),
        Triple("Oila", "Er", "Муж"),
        Triple("Oila", "Xotin", "Жена"),
        Triple("Oila", "Oila", "Семья"),
        Triple("Oila", "Amaki", "Дядя (по отцу)"),
        Triple("Oila", "Tog'a", "Дядя (по матери)"),
        Triple("Oila", "Xola", "Тётя (по матери)"),
        Triple("Taomlar", "Non", "Хлеб"),
        Triple("Taomlar", "Suv", "Вода"),
        Triple("Taomlar", "Choy", "Чай"),
        Triple("Taomlar", "Qahva", "Кофе"),
        Triple("Taomlar", "Sut", "Молоко"),
        Triple("Taomlar", "Go'sht", "Мясо"),
        Triple("Taomlar", "Tovuq", "Курица"),
        Triple("Taomlar", "Baliq", "Рыба"),
        Triple("Taomlar", "Guruch", "Рис"),
        Triple("Taomlar", "Meva", "Фрукты"),
        Triple("Taomlar", "Sabzavot", "Овощи"),
        Triple("Taomlar", "Tuz", "Соль"),
        Triple("Taomlar", "Shakar", "Сахар"),
        Triple("Taomlar", "Mazali!", "Вкусно!"),
        Triple("Taomlar", "Hisob iltimos!", "Счёт, пожалуйста!"),
        Triple("Taomlar", "Ochaman", "Я голоден(на)"),
        Triple("Taomlar", "To'ydim", "Я наелся(ла)"),
        Triple("Transport", "Avtobus", "Автобус"),
        Triple("Transport", "Mashina", "Машина"),
        Triple("Transport", "Poyezd", "Поезд"),
        Triple("Transport", "Samolyot", "Самолёт"),
        Triple("Transport", "Aeroport", "Аэропорт"),
        Triple("Transport", "Vokzal", "Вокзал"),
        Triple("Transport", "Chipta", "Билет"),
        Triple("Transport", "Chipta qancha turadi?", "Сколько стоит билет?"),
        Triple("Transport", "Qachon keladi?", "Когда приедет?"),
        Triple("Transport", "To'xtang!", "Остановите!"),
        Triple("Transport", "Chap tomonga", "Налево"),
        Triple("Transport", "O'ng tomonga", "Направо"),
        Triple("Transport", "To'g'riga", "Прямо"),
        Triple("Transport", "Uzoqmi?", "Далеко?"),
        Triple("Transport", "Yaqin", "Близко"),
        Triple("Transport", "Manzil", "Адрес"),
        Triple("Xarid", "Narx qancha?", "Сколько стоит?"),
        Triple("Xarid", "Qimmat", "Дорого"),
        Triple("Xarid", "Arzon", "Дёшево"),
        Triple("Xarid", "Chegirma bormi?", "Есть скидка?"),
        Triple("Xarid", "Men olaman", "Я возьму"),
        Triple("Xarid", "Karta orqali to'layman", "Оплачу картой"),
        Triple("Xarid", "Naqd pul", "Наличные"),
        Triple("Xarid", "Qopcha", "Пакет"),
        Triple("Xarid", "Do'kon", "Магазин"),
        Triple("Xarid", "Bozor", "Рынок"),
        Triple("Xarid", "Boshqasini ko'rsating", "Покажите другой"),
        Triple("Xarid", "Katta razmer", "Большой размер"),
        Triple("Xarid", "Kichik razmer", "Маленький размер"),
        Triple("Sog'liq", "Shifokor", "Врач"),
        Triple("Sog'liq", "Shifoxona", "Больница"),
        Triple("Sog'liq", "Dorixona", "Аптека"),
        Triple("Sog'liq", "Dori", "Лекарство"),
        Triple("Sog'liq", "Og'riyapti", "Болит"),
        Triple("Sog'liq", "Sog'ligim yomon", "Мне плохо"),
        Triple("Sog'liq", "Yordam bering!", "Помогите!"),
        Triple("Sog'liq", "Jarohat", "Травма"),
        Triple("Sog'liq", "Qon bosimi", "Давление"),
        Triple("Ranglar", "Qizil", "Красный"),
        Triple("Ranglar", "Ko'k", "Синий / Голубой"),
        Triple("Ranglar", "Yashil", "Зелёный"),
        Triple("Ranglar", "Sariq", "Жёлтый"),
        Triple("Ranglar", "Qora", "Чёрный"),
        Triple("Ranglar", "Oq", "Белый"),
        Triple("Ranglar", "Kulrang", "Серый"),
        Triple("Ranglar", "Jigarrang", "Коричневый"),
        Triple("Ranglar", "Binafsha", "Фиолетовый"),
        Triple("Ranglar", "Olovrang", "Оранжевый"),
        Triple("Ranglar", "Pushti", "Розовый"),
        Triple("Foydali iboralar", "Yordam kerak", "Мне нужна помощь"),
        Triple("Foydali iboralar", "Qayerda?", "Где?"),
        Triple("Foydali iboralar", "Qachon?", "Когда?"),
        Triple("Foydali iboralar", "Nima?", "Что?"),
        Triple("Foydali iboralar", "Kim?", "Кто?"),
        Triple("Foydali iboralar", "Nega?", "Почему?"),
        Triple("Foydali iboralar", "Qanday?", "Как?"),
        Triple("Foydali iboralar", "Men tushunmayman", "Я не понимаю"),
        Triple("Foydali iboralar", "Siz ruscha gapirasizmi?", "Вы говорите по-русски?"),
        Triple("Foydali iboralar", "Iltimos, sekinroq", "Медленнее, пожалуйста"),
        Triple("Foydali iboralar", "Xavotir olmang", "Не беспокойтесь"),
        Triple("Foydali iboralar", "Albatta", "Конечно"),
        Triple("Foydali iboralar", "Ehtimol", "Возможно")
    )

    val all: List<Phrase> = raw.map { Phrase(it.second, it.third, it.first) }
}
